name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.7.5
  - anaconda-auth=0.12.3
  - anaconda-cli-base=0.8.1
  - annotated-types=0.6.0
  - archspec=0.2.5
  - backports.tarfile=1.2.0
  - boltons=25.0.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - conda=26.1.1
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.11.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - dbus=1.16.2
  - distro=1.9.0
  - expat=2.7.3
  - fmt=11.2.0
  - frozendict=2.4.6
  - gettext=0.21.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - jansson=2.14
  - jaraco.classes=3.4.0
  - jaraco.context=6.1.0
  - jaraco.functools=4.4.0
  - jeepney=0.7.1
  - keyring=25.7.0
  - ld_impl_linux-64=2.44
  - libarchive=3.8.2
  - libcurl=8.16.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mdurl=0.1.2
  - menuinst=2.4.2
  - more-itertools=10.8.0
  - msgpack-python=1.1.1
  - ncurses=6.5
  - nlohmann_json=3.11.2
  - openssl=3.0.19
  - packaging=25.0
  - pcre2=10.46
  - pkce=1.0.3
  - pluggy=1.5.0
  - pthread-stubs=0.3
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.23
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pydantic-settings=2.12.0
  - pysocks=1.7.1
  - python=3.11.14
  - python-dotenv=1.2.1
  - python_abi=3.11
  - readchar=4.2.1
  - readline=8.3
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - secretstorage=3.4.0
  - semver=3.0.4
  - setuptools=80.10.2
  - shellingham=1.5.4
  - simdjson=3.10.1
  - sqlite=3.51.0
  - tk=8.6.15
  - tomli=2.4.0
  - tomlkit=0.13.3
  - tqdm=4.67.3
  - truststore=0.10.1
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - attrs==23.2.0
      - automat==22.10.0
      - babel==2.10.3
      - bcrypt==3.2.2
      - blinker==1.7.0
      - boto3==1.34.46
      - botocore==1.34.46
      - chardet==5.2.0
      - colorama==0.4.6
      - configobj==5.0.8
      - constantly==23.10.4
      - cryptography==41.0.7
      - httplib2==0.20.4
      - hyperlink==21.0.0
      - incremental==22.10.0
      - jmespath==1.0.1
      - jsonpatch==1.32
      - jsonpointer==2.0
      - jupyter-core==5.3.2
      - launchpadlib==1.11.0
      - lazr-restfulclient==0.14.6
      - lazr-uri==1.0.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - netaddr==0.8.0
      - netifaces==0.11.0
      - oauthlib==3.2.2
      - pexpect==4.9.0
      - pip==26.0.1
      - platformdirs==4.2.0
      - ptyprocess==0.7.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.17.2
      - pyhamcrest==2.1.0
      - pyjwt==2.7.0
      - pyopenssl==23.2.0
      - pyparsing==3.1.1
      - pyrsistent==0.20.0
      - pyserial==3.5
      - python-dateutil==2.8.2
      - python-magic==0.4.27
      - pytz==2024.1
      - rich==13.7.1
      - s3transfer==0.10.1
      - service-identity==24.1.0
      - six==1.16.0
      - traitlets==5.5.0
      - tree-sitter==0.23.2
      - twisted==24.3.0
      - urllib3==2.0.7
      - wadllib==1.3.6
      - zope-interface==6.1
prefix: /home/zcheng06/miniconda3
